apiVersion: v1
kind: Pod
metadata:
  name: mongo-client
  labels:
    app: mongo-client
spec:
  containers:
    - image: vendeq.azurecr.io/testclient:v5
      name: main
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-client
spec:
  selector:
    app: mongo-client
  ports:
    - port: 5000
