apiVersion: v1
kind: Pod
metadata:
  name: mongo-server
  labels:
    app: mongo-server
spec:
  containers:
    - image: mongo:4.0.12-xenial
      name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-server
spec:
  selector:
    app: mongo-server
  ports:
    - port: 27017
